"""Storage backend protocol."""

from __future__ import annotations

from typing import Any, Protocol, Iterable


class StoreBackend(Protocol):
    def backend_name(self) -> str: ...

    def current_path(self) -> str: ...

    def close(self) -> None: ...

    def upsert_topic_detail(self, topic_summary: dict[str, Any], topic: dict[str, Any]) -> None: ...

    def get_existing_post_ids(self, topic_id: int, post_ids: Iterable[int]) -> set[int]: ...

    def insert_posts(self, topic_id: int, posts: Iterable[dict[str, Any]]) -> None: ...

    def upsert_topic_crawl_state(self, topic_id: int, last_synced_post_number: int, last_stream_len: int) -> None: ...

    def get_last_synced_post_number(self, topic_id: int) -> int: ...

    def get_last_read_post_number(self, topic_id: int) -> int: ...

    def update_last_read_post_number(self, topic_id: int, last_read_post_number: int) -> None: ...

    def begin_watch_cycle(self, cycle_id: str, started_at: str) -> None: ...

    def finish_watch_cycle(
        self,
        cycle_id: str,
        *,
        ended_at: str,
        topics_fetched: int,
        topics_entered: int,
        posts_fetched: int,
        notifications_sent: int,
        success: bool,
        error_text: str = "",
    ) -> None: ...

    def get_sent_notification_ids(self, ids: Iterable[int]) -> set[int]: ...

    def mark_notifications_sent(self, items: Iterable[dict[str, Any]]) -> None: ...

    def inc_stat(self, field: str, delta: int = 1) -> None: ...

    def get_stats_total(self) -> dict[str, int]: ...

    def get_stats_today(self) -> dict[str, int]: ...

    def get_plugin_daily_count(self, plugin_id: str, action: str) -> int: ...

    def inc_plugin_daily_count(self, plugin_id: str, action: str, delta: int = 1) -> int: ...

    def get_plugin_daily_counts(self, plugin_id: str) -> dict[str, int]: ...

    def plugin_once_exists(self, plugin_id: str, key: str) -> bool: ...

    def mark_plugin_once(self, plugin_id: str, key: str) -> None: ...

    def count_plugin_once_marks(self, plugin_id: str) -> int: ...

    def get_plugin_kv(self, plugin_id: str, key: str, default: object = None) -> object: ...

    def set_plugin_kv(self, plugin_id: str, key: str, value: object) -> None: ...

    def list_plugin_kv_keys(self, plugin_id: str) -> list[str]: ...

    def log_plugin_action(
        self,
        *,
        cycle_id: str,
        plugin_id: str,
        hook_name: str,
        action: str,
        status: str,
        reason: str = "",
        topic_id: int | None = None,
        post_id: int | None = None,
        extra: dict[str, Any] | None = None,
    ) -> None: ...
